.TH OTRTOOL 1 2021-01-26 ZOMG "otrtool Manual"

.\" ********************************************************************
.\" ********************************************************************
.SH NAME
otrtool \- decrypts otrkeys from onlinetvrecorder.com

.SH SYNOPSIS

.B otrtool
.B \-i
.I otrkey-files

.br
.B otrtool
.B \-f
.RB [\| \-e
.IR email \|]
.RB [\| \-p
.IR password \|]
.I otrkey-files

.br
.B otrtool
.B \-x
.RB [\| \-u \|]
.RB [\| \-e
.IR email \|]
.RB [\| \-p
.IR password \|]
.RB [\| \-k
.IR keyphrase \|]
.RS 11
.br
.RB [\| \-D
.IR output-folder \|]
.RB [\| \-O
.IR output-file \|]
.I otrkey-files
.RE

.br
.B otrtool
.B \-y
.I otrkey-files

.br
.B otrtool
.RB [\| \-h \|]
.RB [\| \-v \|]

.\" ********************************************************************
.\" ********************************************************************
.SH DESCRIPTION
.B otrtool
aims to provide an open source tool to deal with otrkey\-files from
onlinetvrecorder.com.
It is able to decrypt them using keys it fetches from OTR's
servers while authenticating with user-supplied login credentials.
For basic usage, see \fBEXAMPLES\fR below.

.\" ********************************************************************
.\" ********************************************************************
.SH OPTIONS

.\" ********************************************************************
.SS "Modes of operation"

.TP
.B \-i
Display information about
.I otrkey-files

.TP
.B \-f
Fetch keyphrase for
.I otrkey-files

.TP
.B \-x
Fetch keyphrase for
.I otrkey-files
and decrypt them

.TP
.B \-y
Verify the integrity of
.I otrkey-files
without decrypting


.\" ********************************************************************
.SS "General options"

.TP
.B \-h
Display help

.TP
.B \-v
Be verbose


.\" ********************************************************************
.SS "Decrypt options"

.TP
.BI \-k \ keyphrase
Do not fetch keyphrase, instead use
.I keyphrase

.TP
.BI \-D \ output-folder
Save decrypted file to
.I output-folder/otr-style-filename.mpg.whatever

.TP
.BI \-O \ output-file
Save decrypted file to
.I output-file
.br
This overrides
.B -D

.TP
.BI \-u
Delete (unlink)
.I otrkey-files
after successful decryption.
This option is only applied if both input and output are regular files.


.\" ********************************************************************
.SS "Fetch options"

.TP
.BI \-e \ email
Authenticate using
.I email
as e-mail address

.TP
.BI \-p \ password
Authenticate using
.I password
as password


.\" ********************************************************************
.SS "Miscellaneous options"

.TP
.B \-g
Output machine-readable progress information on stdout
.br
(for use by GUIs)


.\" ********************************************************************
.SS "Testing, debugging and benchmarking"

These options might change their behaviour in the future.

.TP
.BI \-T \ n
In decrypt mode, if multithreading is available and \fIn\fR is greater
than zero, use \fIn\fR worker threads, within limits.
Setting this option to an integer other than zero also prevents
\fBotrtool\fR from touching its \fBnice\fR(1) and \fBionice\fR(1)
[Linux] values.


.\" ********************************************************************
.\" ********************************************************************
.SH "EXAMPLES"

Decrypt a single otrkey file.
If you have not decrypted that file before, you will be asked for your
e-mail address and password:
.PP
.nf
.RS
.B otrtool \-x \fRsomefile.otrkey
.RE
.fi

.PP
Decrypt several otrkey files in your "Downloads" directory and delete each of
them afterwards. Output files will be stored in your "Movies" directory:
.PP
.nf
.RS
.B otrtool \-x \-u \-D \fRMovies Downloads/*.otrkey
.RE
.fi


.\" ********************************************************************
.\" ********************************************************************
.SH "FILES"
Where multiple file names are given, the first existing file is used.
If none exists, the first alternative is used.
$XDG_DATA_HOME defaults to ~/.local/share.

.TP
.I ~/.otrkey_cache
.TQ
.I $XDG_DATA_HOME/otrtool/otrkey_cache
Key cache. Currently, the only way to disable this feature is to disallow
\fBotrtool\fR to read or write this file by using \fBchmod\fR(1)
or similar means.


.\" ********************************************************************
.\" ********************************************************************
.SH "CONTACT"

.TP
.B Homepage:
http://otrtool.github.io/otrtool/

.TP
.B Repository:
http://github.com/otrtool/otrtool

.TP
.B Bug tracker:
http://github.com/otrtool/otrtool/issues

.TP
.B E-mail:
eshrdlu
.R AT
yandex
.R DOT
com (de, en)

.RE

Bug reports, feature requests, patches and package maintainers are always welcome.

