/*
  Blowfish for otrtool

  Generate the 8336 hexadecimal digits of pi that are
  needed to initialize the Blowfish algorithm
  using the Bailey-Borwein-Plouffe formula
  as described in: https://giordano.github.io/blog/2017-11-21-hexadecimal-pi/

  This little helper program is only used at compile-time.
*/
#include <stdio.h>
#include <stdint.h>

uint32_t modpow(uint32_t b, uint32_t e, uint32_t m)
{
  uint32_t x = 1;

  while (e > 0) {
    if (e % 2 == 0) {
      b = (uint64_t)b*b % m;
      e /= 2;
    }
    else {
      x = (uint64_t)b * x % m;
      e -= 1;
    }
  }
  return x;
}

double s(int n, int j)
{
  int k;
  double x = 0.0;

  for (k=0; k <= n; k++) {
    x += (double)modpow(16, n-k, 8*k+j) / (8*k+j);
    if (x > 1.0) x -= 1.0;
  }

  double d = 1.0;
  double x0 = -1.0;
  for (; x - x0 > 1e-12; k++) {
    x0 = x;
    d /= 16;
    x += d / (8.0*k+j);
  }

  return x;
}

#define TICKS_PER_PERCENT ((8336ul+1)*8336/2)
unsigned long ticks = 0;
int percent = 0;

int pi_digit16(int n)
{
  double d = 16*(4*s(n,1) - 2*s(n,4) - s(n,5) - s(n,6));
  if (d < 0) d -= 1.0;

  ticks += 100ul*(n+1);
  if (ticks >= TICKS_PER_PERCENT) {
    ticks -= TICKS_PER_PERCENT;
    fprintf(stderr, "%d%%\r", ++percent);
    fflush(stderr);
  }

  return (unsigned)(int)d % 16;
}

void print_constants(int *digi, int n, int indent)
{
  int i, j;
  uint32_t x;

  for (i=0; i<n; i++) {
    if (i % 4 == 0) {
      if (i > 0)
        printf(",\n");
      printf("%*c", indent, ' ');
    }
    else
      printf(", ");
    for (x=0, j=0; j<8; j++)
      x = 16*x + pi_digit16((*digi)++);
    printf("0x%.8Xul", x);
  }
}

int main(void)
{
  int n = 0;
  int i;

  printf(
    "/* initial subkeys and S-boxes for Blowfish\n"
    "   generated by blowfish_gen.c */\n"
    "static const uint32_t P0[18] = {\n");
  print_constants(&n, 18, 2);
  printf(
    "\n};\n"
    "static const uint32_t S0[4][256] = {\n");
  for (i=0; i<4; i++) {
    printf("  {\n");
    print_constants(&n, 256, 4);
    printf("\n  }%s\n", (i < 3) ? "," : "");
  }
  printf("};\n");
}
